### ISSUE TITLE
where is the code of run the yolo5's tnn model and get the bbox ?

### ISSUE THREAD

**Issue by henbucuoshanghai** [cmdbug/TNN_Demo#11]

**Comment by cmdbug** [comment]
Android: https://github.com/cmdbug/TNN_Demo/blob/main/android_TNN_Demo/app/src/main/cpp/Yolov5.cpp
iOS: https://github.com/cmdbug/TNN_Demo/blob/main/iOS_TNN_Demo/TNNDemo/Yolov5.mm

**Comment by henbucuoshanghai** [comment]
opencv is cv2.imread&nbsp; one image,how about the code in yolov5.mm?


    TNN_NS::MatConvertParam,,,&nbsp; how to read one image??




/ 转换大小
    TNN_NS::ResizeParam param;
    param.type = TNN_NS::InterpType::INTERP_TYPE_NEAREST;
    status = TNN_NS::MatUtils::Resize(*input_mat, *resize_mat, param, command_queue);
    

    // 输入数据
    TNN_NS::MatConvertParam input_cvt_param;
    input_cvt_param.scale = {1.0 / 255, 1.0 / 255, 1.0 / 255, 0.0};
    input_cvt_param.bias = {0.0, 0.0, 0.0, 0.0};
    status = YoloV5::instance-&gt;SetInputMat(resize_mat, input_cvt_param);

**Comment by cmdbug** [comment]
For the data pointer of the incoming picture, you can also see the example of the official demo.

**Comment by henbucuoshanghai** [comment]
你好&nbsp; &nbsp;你的nanodet跑通了，模型代码用你的&nbsp; 感谢 很厉害
但是自己训练了一个只一类的nanodet&nbsp; 用官方的export导出后tnn&nbsp; 更换掉类别后代码报错 请问怎么回事？？感激！！
