### ISSUE TITLE
yolo5的模型转换需要修改一些东西,，请问nanodet需要修改的多吗？

### ISSUE THREAD

**Issue by henbucuoshanghai** [cmdbug/TNN_Demo#13]
nandodet官网直接export出onnx，然后直接转成的tnn可以直接用在此处？

**Comment by cmdbug** [comment]
nanodet早期版本直接onnx -> tnn就可以了，最新版没测试。

**Comment by henbucuoshanghai** [comment]
ok  tks

**Comment by henbucuoshanghai** [comment]
你好&nbsp; &nbsp;tnn官网很多模型confg&nbsp; &nbsp;模型之间略有差异&nbsp;&nbsp;
请问转换模型后，本文cpp后处理基本不用修改？
