### ISSUE TITLE
关于检测类别问题

### ISSUE THREAD

**Issue by Zengyf-CVer** [cmdbug/TNN_Demo#7]
@cmdbug 
#### 大神，我的模型可以正常运行 ，但是检测的类别依然按照coco类别显示的，类别索引是对的，我把label数组改成自己的了，但是依然显示的是coco的label。

```c
# yolov5.h文件
    std::vector<std::string> labels{"prohibitory", "warning", "mandatory"};
private:
    std::shared_ptr<tnn::TNN> net;
    std::shared_ptr<TNN_NS::Instance> instance;
    TNN_NS::DeviceType device_type;

    int net_width = 640;
    int net_height = 640;
    int num_class = 3;
```
#### 比如，索引号检测是0，应该显示`prohibitory`，结果显示的是coco中的`person`，求大神解答一下

**Comment by Zengyf-CVer** [comment]
Android Studio中缓存清除了，并且重新编译，重新安装APP，结果还是显示coco类别

**Comment by cmdbug** [comment]
标签文字是读取的java里面的，不是h的。
./TNN_Demo/android_TNN_Demo/app/src/main/java/com/wzt/tnn/model/BoxInfo.java

**Comment by Zengyf-CVer** [comment]
> 标签文字是读取的java里面的，不是h的。
> ./TNN_Demo/android_TNN_Demo/app/src/main/java/com/wzt/tnn/model/BoxInfo.java

谢谢大神
